# Generated by Django 5.2.8 on 2025-11-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_venue',
            field=models.TextField(blank=True, help_text='About the venue - venue information and details'),
        ),
        migrations.AddField(
            model_name='event',
            name='gates_open_time',
            field=models.TimeField(blank=True, help_text='Time when gates/doors open', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Event terms and conditions'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='About this event - detailed description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(help_text='Event start time'),
        ),
    ]
