# Generated by Django 5.2.8 on 2025-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_about_venue_event_gates_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as featured/trending event'),
        ),
    ]
