# Generated by Django 5.2.8 on 2025-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for the event - displayed on event detail page and listings', null=True, upload_to='events/images/', verbose_name='Main Event Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for tickets (e.g., 100.00). This will be displayed on the web app.', max_digits=10, null=True, verbose_name='Starting Ticket Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='about_venue',
            field=models.TextField(blank=True, help_text='Information about the venue - this will be displayed on the event detail page', verbose_name='About The Venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the event (YYYY-MM-DD)', verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description about the event - this will be displayed on the event detail page', verbose_name='About This Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gates_open_time',
            field=models.TimeField(blank=True, help_text='Time when gates/doors open (e.g., 18:00)', null=True, verbose_name='Gates Open Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Terms and conditions for this event - this will be displayed on the event detail page', verbose_name='Event Terms and Conditions'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(help_text='Start time of the event (HH:MM format, e.g., 20:00)', verbose_name='Event Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Event Title'),
        ),
    ]
