# Generated by Django 5.2.8 on 2025-11-11 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ticketcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transfer_fee_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='flat', help_text='Type of transfer fee: percentage of ticket price or flat amount', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='transfer_fee_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, help_text='Transfer fee amount: percentage (e.g., 5.00 for 5%) or flat amount (e.g., 50.00)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
