# Generated by Django 5.2.8 on 2025-11-11 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_transfer_fee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission_rate_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='percentage', help_text='Type of commission: percentage of revenue or flat amount per ticket', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='commission_rate_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Commission rate: percentage (e.g., 10.00 for 10%) or flat amount (e.g., 50.00 per ticket)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
