# Generated by Django 5.2.7 on 2025-11-22 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_commission_rate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='child_eligibility_enabled',
            field=models.BooleanField(default=False, help_text='Enable child eligibility for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='child_eligibility_max_age',
            field=models.PositiveIntegerField(blank=True, help_text="Maximum age for child eligibility (used with 'between' or 'less_than' rules)", null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='child_eligibility_min_age',
            field=models.PositiveIntegerField(blank=True, help_text="Minimum age for child eligibility (used with 'between' or 'more_than' rules)", null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='child_eligibility_rule_type',
            field=models.CharField(blank=True, choices=[('between', 'Between ages (min–max)'), ('less_than', 'Less than (age < X)'), ('more_than', 'More than (age > X)')], help_text='Type of age rule for child eligibility', max_length=20, null=True),
        ),
    ]
