# Generated by Django 5.2.8 on 2025-11-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_child_eligibility_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='color',
            field=models.CharField(default='#10B981', help_text='Hex color code for this ticket category (e.g., #10B981 for green)', max_length=7, verbose_name='Color'),
        ),
    ]
