# Generated by Django 5.2.8 on 2025-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_ticketcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_ticket_limit_unlimited',
            field=models.BooleanField(default=False, help_text='Allow attendees to purchase up to the total number of available tickets (no per-order cap)'),
        ),
    ]
