# Generated by Django 5.2.8 on 2025-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_ticket_limit_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artist_name',
            field=models.CharField(blank=True, db_index=True, help_text='Name of the artist or singer performing at this event', max_length=200, verbose_name='Artist/Singer Name'),
        ),
    ]
