# Generated by Django 5.2.8 on 2025-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_add_artist_name_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_layout_image',
            field=models.ImageField(blank=True, help_text="Layout image of the venue for this event - displayed in a popup when users click 'View Venue Layout'", null=True, upload_to='events/venue_layouts/', verbose_name='Venue Layout Image'),
        ),
    ]
