# Generated by Django 5.2.8 on 2025-12-02 14:01

from django.db import migrations, models


def migrate_organizer_data(apps, schema_editor):
    """
    Migrate data from organizer ForeignKey to organizers ManyToManyField.
    """
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        # Get the old organizer value
        old_organizer_id = event.organizer_id if hasattr(event, 'organizer_id') else None
        if old_organizer_id:
            # Add the organizer to the ManyToManyField
            event.organizers.add(old_organizer_id)


def reverse_migrate_organizer_data(apps, schema_editor):
    """
    Reverse migration: move first organizer from ManyToManyField back to ForeignKey.
    Note: This will only preserve the first organizer if multiple exist.
    """
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        first_organizer = event.organizers.first()
        if first_organizer:
            event.organizer_id = first_organizer.id
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_venue_layout_image_to_event'),
        ('users', '0008_add_organizer_edit_request'),
    ]

    operations = [
        # Step 1: Add the new ManyToManyField (temporarily nullable)
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='Event organizers (optional, can have multiple)', related_name='events', to='users.organizer', verbose_name='Organizers'),
        ),
        # Step 2: Migrate data from old field to new field
        migrations.RunPython(migrate_organizer_data, reverse_migrate_organizer_data),
        # Step 3: Remove the old ForeignKey field and index
        migrations.RemoveIndex(
            model_name='event',
            name='events_organiz_1c7a2e_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
