# Generated by Django 5.2.7 on 2025-12-06 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_change_organizer_to_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_tickets',
            field=models.IntegerField(help_text='Total number of tickets for this event. Set to 0 to mark as sold out.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
