# Generated by Django 5.2.8 on 2025-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_allow_zero_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bathroom',
            field=models.BooleanField(default=False, help_text='Bathroom facilities available at the venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='non_smoking',
            field=models.BooleanField(default=False, help_text='Non-smoking policy at the venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='parking',
            field=models.BooleanField(default=False, help_text='Parking facilities available at the venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='wheelchair_access',
            field=models.BooleanField(default=False, help_text='Wheelchair accessibility available at the venue'),
        ),
    ]
