# Generated by Django 5.2.8 on 2025-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_bathroom_event_non_smoking_event_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_doors_time',
            field=models.TimeField(blank=True, help_text='Time when doors close and event is considered completed (e.g., 23:00)', null=True, verbose_name='Closed Doors Time'),
        ),
    ]
