# Generated by Django 5.2.8 on 2025-12-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_closed_doors_time'),
        ('finances', '0003_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deductions',
            field=models.ManyToManyField(blank=True, help_text="Deductions applied to this event's ticket sales revenue", related_name='events', to='finances.deduction', verbose_name='Deductions'),
        ),
    ]
