# Generated by Django 5.2.8 on 2025-12-11 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_deductions_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marketplace_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed price for marketplace ticket listings for this event (in EGP). Leave empty to use global default.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
