# Generated by Django 5.2.8 on 2025-11-06 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0002_merchant_address_merchant_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_changes', models.TextField(help_text='Description of requested changes')),
                ('file_attachments', models.TextField(blank=True, help_text='JSON serialized list of file paths/URLs', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/reason for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='users.organizer')),
            ],
            options={
                'verbose_name': 'Event Edit Request',
                'verbose_name_plural': 'Event Edit Requests',
                'db_table': 'event_edit_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='event_edit__event_i_15bc93_idx'), models.Index(fields=['organizer'], name='event_edit__organiz_3ef42d_idx'), models.Index(fields=['status'], name='event_edit__status_784c5c_idx'), models.Index(fields=['created_at'], name='event_edit__created_01035f_idx')],
            },
        ),
    ]
