# Generated by Django 5.2.8 on 2025-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventeditrequest',
            name='new_event_image',
            field=models.ImageField(blank=True, help_text='New event image file', null=True, upload_to='event_edit_requests/'),
        ),
        migrations.AddField(
            model_name='eventeditrequest',
            name='requested_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured request data for specific edit types', null=True),
        ),
    ]
