# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('refunded', 'Refunded'), ('banned', 'Banned')], db_index=True, default='valid', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='customers.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_tickets', to='customers.customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='tickets.ticket')),
                ('to_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Ticket Transfer',
                'verbose_name_plural': 'Ticket Transfers',
                'db_table': 'ticket_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event'], name='tickets_event_i_f58fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer'], name='tickets_custome_321035_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_status_fbbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_ticket__4c9624_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['purchase_date'], name='tickets_purchas_2580ae_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='tickets_event_i_30e5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['ticket'], name='ticket_tran_ticket__880028_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['transfer_date'], name='ticket_tran_transfe_869e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['status'], name='ticket_tran_status_af5867_idx'),
        ),
    ]
