# Generated by Django 5.2.8 on 2025-11-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_dependent_customer_fees_paid_customer_mobile_number_and_more'),
        ('tickets', '0002_ticket_assigned_email_ticket_assigned_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='Original purchaser (who paid for the ticket)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(help_text='Current ticket owner (may be buyer or assigned person)', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='customers.customer'),
        ),
    ]
