# Generated by Django 5.2.8 on 2025-11-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_emergency_contact_blood_type_fields'),
        ('tickets', '0003_ticket_buyer_alter_ticket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettransfer',
            name='to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to='customers.customer'),
        ),
    ]
