# Generated by Django 5.2.7 on 2025-11-22 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_make_tickettransfer_to_customer_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Registration Token',
                'verbose_name_plural': 'Ticket Registration Tokens',
                'db_table': 'ticket_registration_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='ticket_regi_token_2cbfdd_idx'), models.Index(fields=['phone_number'], name='ticket_regi_phone_n_678d96_idx'), models.Index(fields=['expires_at'], name='ticket_regi_expires_3da9c7_idx'), models.Index(fields=['used'], name='ticket_regi_used_bbca61_idx')],
            },
        ),
    ]
