# Generated by Django 5.2.8 on 2025-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketregistrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='child_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the child', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_child',
            field=models.BooleanField(default=False, help_text='Ticket holder has a child'),
        ),
    ]
