# Generated by Django 5.2.7 on 2025-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_labels_to_customer'),
        ('events', '0013_change_organizer_to_manytomany'),
        ('tickets', '0006_add_child_fields_to_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_black_card',
            field=models.BooleanField(db_index=True, default=False, help_text="Black Card Customer ticket - doesn't count towards event capacity or organizer dashboard"),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_black_card'], name='tickets_is_blac_af3178_idx'),
        ),
    ]
