# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_labels_to_customer'),
        ('tickets', '0007_ticket_is_black_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMarketplaceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(help_text='The seller (current ticket owner)', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='customers.customer', db_index=True)),
                ('ticket', models.ForeignKey(help_text='The ticket being listed', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='tickets.ticket', unique=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Ticket Marketplace Listing',
                'verbose_name_plural': 'Ticket Marketplace Listings',
                'db_table': 'ticket_marketplace_listings',
                'ordering': ['-listed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketmarketplacelisting',
            index=models.Index(fields=['ticket'], name='ticket_mark_ticket__idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmarketplacelisting',
            index=models.Index(fields=['customer'], name='ticket_mark_custome_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmarketplacelisting',
            index=models.Index(fields=['listed_at'], name='ticket_mark_listed__idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmarketplacelisting',
            index=models.Index(fields=['is_active'], name='ticket_mark_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmarketplacelisting',
            index=models.Index(fields=['is_active', 'listed_at'], name='ticket_mark_is_acti_listed_idx'),
        ),
    ]

