# Generated by Django 5.2.8 on 2025-12-11 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketmarketplacelisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_allowed_price', models.DecimalField(decimal_places=2, default=10000.0, help_text='Maximum allowed price for marketplace ticket listings (in EGP)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Settings',
                'verbose_name_plural': 'Marketplace Settings',
                'db_table': 'marketplace_settings',
            },
        ),
        migrations.RenameIndex(
            model_name='ticketmarketplacelisting',
            new_name='ticket_mark_ticket__e05871_idx',
            old_name='ticket_mark_ticket__idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmarketplacelisting',
            new_name='ticket_mark_custome_825574_idx',
            old_name='ticket_mark_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmarketplacelisting',
            new_name='ticket_mark_listed__34c6b4_idx',
            old_name='ticket_mark_listed__idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmarketplacelisting',
            new_name='ticket_mark_is_acti_14647e_idx',
            old_name='ticket_mark_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmarketplacelisting',
            new_name='ticket_mark_is_acti_164d64_idx',
            old_name='ticket_mark_is_acti_listed_idx',
        ),
        migrations.AddField(
            model_name='ticketmarketplacelisting',
            name='seller_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price set by the seller for this listing (display only)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
