# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('total_tickets_available', models.PositiveIntegerField(default=0)),
                ('total_attendees', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cut_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('registered_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('inactive_users', models.PositiveIntegerField(default=0)),
                ('recurrent_users', models.PositiveIntegerField(default=0)),
                ('total_cards', models.PositiveIntegerField(default=0)),
                ('active_cards', models.PositiveIntegerField(default=0)),
                ('inactive_cards', models.PositiveIntegerField(default=0)),
                ('expired_cards', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
                'db_table': 'dashboard_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='dashboard_s_date_87151c_idx')],
            },
        ),
    ]
