# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('events', '0001_initial'),
        ('nfc_cards', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('event_title', models.CharField(blank=True, max_length=200)),
                ('entry_point', models.CharField(blank=True, max_length=100)),
                ('card_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=20)),
                ('scan_result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid')], db_index=True, max_length=20)),
                ('scan_type', models.CharField(choices=[('nfc', 'NFC'), ('qr', 'QR Code'), ('manual', 'Manual')], db_index=True, max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('scanner', 'Scanner')], max_length=20)),
                ('operator_role', models.CharField(blank=True, max_length=50)),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('signal_strength', models.CharField(blank=True, max_length=50)),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True)),
                ('network_status', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('syncing', 'Syncing')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to='customers.customer')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to='events.event')),
                ('nfc_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to='nfc_cards.nfccard')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Check-in Log',
                'verbose_name_plural': 'Check-in Logs',
                'db_table': 'checkin_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='checkin_log_timesta_4d9140_idx'), models.Index(fields=['event'], name='checkin_log_event_i_3ddd9b_idx'), models.Index(fields=['customer'], name='checkin_log_custome_7a3d1a_idx'), models.Index(fields=['nfc_card'], name='checkin_log_nfc_car_b9af53_idx'), models.Index(fields=['scan_result'], name='checkin_log_scan_re_d567db_idx'), models.Index(fields=['scan_type'], name='checkin_log_scan_ty_7fe765_idx'), models.Index(fields=['timestamp', 'event'], name='checkin_log_timesta_4ce7a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_role', models.CharField(blank=True, db_index=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('event', 'Event'), ('ticket', 'Ticket'), ('customer', 'Customer'), ('user', 'User'), ('financial', 'Financial'), ('system', 'System'), ('other', 'Other')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending')], db_index=True, default='SUCCESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='system_logs_timesta_84e60c_idx'), models.Index(fields=['user'], name='system_logs_user_id_85bc8b_idx'), models.Index(fields=['category'], name='system_logs_categor_7ec442_idx'), models.Index(fields=['severity'], name='system_logs_severit_343258_idx'), models.Index(fields=['timestamp', 'category'], name='system_logs_timesta_94761d_idx'), models.Index(fields=['timestamp', 'severity'], name='system_logs_timesta_d61d34_idx')],
            },
        ),
    ]
