# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], db_index=True, default='active', max_length=20)),
                ('registration_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attended_events', models.PositiveIntegerField(default=0)),
                ('is_recurrent', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['email'], name='customers_email_92e882_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['status'], name='customers_status_47bd31_idx'), models.Index(fields=['is_recurrent'], name='customers_is_recu_8d58c3_idx'), models.Index(fields=['registration_date'], name='customers_registr_3b03b8_idx')],
            },
        ),
    ]
