# Generated by Django 5.2.8 on 2025-11-06 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dependent',
                'verbose_name_plural': 'Dependents',
                'db_table': 'dependents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='fees_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether customer has paid registration fees'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, help_text='Mobile number for webapp authentication', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for webapp authentication', max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['mobile_number'], name='customers_mobile__009b0e_idx'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='dependent',
            index=models.Index(fields=['customer'], name='dependents_custome_177a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='dependent',
            index=models.Index(fields=['name'], name='dependents_name_5201e0_idx'),
        ),
    ]
