# Generated by Django 5.2.8 on 2025-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_dependent_customer_fees_paid_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blood_type',
            field=models.CharField(blank=True, help_text='Blood type (e.g., A+, B-, O+, AB+)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, help_text='Emergency contact mobile number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Customer profile image', null=True, upload_to='customer_profiles/'),
        ),
    ]
