# Generated by Django 5.2.7 on 2025-11-22 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_emergency_contact_blood_type_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='National ID number (required for registration)', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['national_id'], name='customers_nationa_0499ab_idx'),
        ),
    ]
