# Generated by Django 5.2.8 on 2025-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_add_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from EVS (Event Verification System) or other sources', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='National ID number (optional for registration)', max_length=50, null=True, unique=True),
        ),
    ]
