# Generated by Django 5.2.8 on 2025-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_add_notes_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text="Custom labels assigned by admin (e.g., ['VIP', 'Premium'])"),
        ),
    ]
