# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(db_index=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_used', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('card_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='customers.customer')),
            ],
            options={
                'verbose_name': 'NFC Card',
                'verbose_name_plural': 'NFC Cards',
                'db_table': 'nfc_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='nfc_cards.nfccard')),
            ],
            options={
                'verbose_name': 'NFC Card Transaction',
                'verbose_name_plural': 'NFC Card Transactions',
                'db_table': 'nfc_card_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['serial_number'], name='nfc_cards_serial__2eb2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['customer'], name='nfc_cards_custome_14b3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['status'], name='nfc_cards_status_33079b_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['expiry_date'], name='nfc_cards_expiry__74e4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['status', 'expiry_date'], name='nfc_cards_status_c27213_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccardtransaction',
            index=models.Index(fields=['card'], name='nfc_card_tr_card_id_b50b16_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccardtransaction',
            index=models.Index(fields=['timestamp'], name='nfc_card_tr_timesta_0841ab_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccardtransaction',
            index=models.Index(fields=['transaction_type'], name='nfc_card_tr_transac_4cd408_idx'),
        ),
    ]
