# Generated by Django 5.2.8 on 2025-11-06 12:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_dependent_customer_fees_paid_customer_mobile_number_and_more'),
        ('nfc_cards', '0001_initial'),
        ('users', '0002_merchant_address_merchant_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCardAutoReload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, help_text='Balance threshold to trigger auto-reload', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reload_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to reload when threshold is reached', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NFC Card Auto Reload',
                'verbose_name_plural': 'NFC Card Auto Reloads',
                'db_table': 'nfc_card_auto_reload',
            },
        ),
        migrations.AddField(
            model_name='nfccard',
            name='assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When card was assigned to customer', null=True),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When card was delivered to customer', null=True),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='hashed_code',
            field=models.CharField(blank=True, help_text='Hashed code for card writing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant who assigned this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to='users.merchant'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['merchant'], name='nfc_cards_merchan_7fd23b_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['assigned_at'], name='nfc_cards_assigne_101d99_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['delivered_at'], name='nfc_cards_deliver_502eff_idx'),
        ),
        migrations.AddField(
            model_name='nfccardautoreload',
            name='nfc_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reload_settings', to='nfc_cards.nfccard'),
        ),
        migrations.AddIndex(
            model_name='nfccardautoreload',
            index=models.Index(fields=['nfc_card'], name='nfc_card_au_nfc_car_4f3158_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccardautoreload',
            index=models.Index(fields=['enabled'], name='nfc_card_au_enabled_513d48_idx'),
        ),
    ]
