# Generated by Django 5.2.8 on 2025-12-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_add_notes_to_customer'),
        ('nfc_cards', '0002_nfccardautoreload_nfccard_assigned_at_and_more'),
        ('users', '0008_add_organizer_edit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='collector',
            field=models.ForeignKey(blank=True, help_text='Person authorized to collect this card on behalf of the owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_nfc_cards', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Card owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['collector'], name='nfc_cards_collect_3f0a25_idx'),
        ),
    ]
