# Generated by Django 5.2.8 on 2025-12-09 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_labels_to_customer'),
        ('nfc_cards', '0005_fix_invalid_merchant_references'),
        ('users', '0009_add_usher_zones_ticket_categories_team_leader'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nfccard',
            name='nfc_cards_status_c27213_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfccard',
            name='nfc_cards_assigne_101d99_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfccard',
            name='nfc_cards_deliver_502eff_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfccard',
            name='nfc_cards_collect_3f0a25_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfccardtransaction',
            name='nfc_card_tr_card_id_b50b16_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfccardtransaction',
            name='nfc_card_tr_timesta_0841ab_idx',
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='collector',
            field=models.ForeignKey(blank=True, help_text='Authorized person to collect this card on behalf of the owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cards', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='hashed_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='users.merchantlocation'),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nfccardtransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nfccardtransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nfccardtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfccardtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('reload', 'Reload'), ('purchase', 'Purchase'), ('refund', 'Refund')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['status', 'customer'], name='nfc_cards_status_9ed7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccardtransaction',
            index=models.Index(fields=['nfc_card'], name='nfc_card_tr_nfc_car_211c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccardtransaction',
            index=models.Index(fields=['created_at'], name='nfc_card_tr_created_af23b0_idx'),
        ),
    ]
