# Generated by Django 5.2.8 on 2025-11-13 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_event_commission_rate_type_and_more'),
        ('users', '0004_usher_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usher_leaves', to='events.event')),
                ('usher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_time_leaves', to='users.usher')),
            ],
            options={
                'verbose_name': 'Part Time Leave',
                'verbose_name_plural': 'Part Time Leaves',
                'db_table': 'usher_part_time_leaves',
                'ordering': ['-leave_time'],
                'indexes': [models.Index(fields=['usher'], name='usher_part__usher_i_ae456c_idx'), models.Index(fields=['event'], name='usher_part__event_i_d9c221_idx'), models.Index(fields=['leave_time'], name='usher_part__leave_t_e47018_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('technical', 'Technical Issue'), ('security', 'Security Concern'), ('customer', 'Customer Issue'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('description', models.TextField()),
                ('card_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ticket_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('customer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_reports', to='events.event')),
                ('usher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_reports', to='users.usher')),
            ],
            options={
                'verbose_name': 'Scan Report',
                'verbose_name_plural': 'Scan Reports',
                'db_table': 'usher_scan_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usher'], name='usher_scan__usher_i_15e9a1_idx'), models.Index(fields=['event'], name='usher_scan__event_i_3211d3_idx'), models.Index(fields=['report_type'], name='usher_scan__report__3a0f73_idx'), models.Index(fields=['status'], name='usher_scan__status_c1cf9d_idx'), models.Index(fields=['created_at'], name='usher_scan__created_d3c14b_idx')],
            },
        ),
    ]
