# Generated by Django 5.2.8 on 2025-11-06 12:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_dependent_customer_fees_paid_customer_mobile_number_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('nfc_card', 'NFC Card'), ('digital_wallet', 'Digital Wallet'), ('bank_transfer', 'Bank Transfer')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('transaction_id', models.CharField(db_index=True, help_text='External payment gateway transaction ID', max_length=100, unique=True)),
                ('payment_gateway_response', models.TextField(blank=True, help_text='Raw response from payment gateway', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='customers.customer')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='payment_tra_custome_c3eadf_idx'), models.Index(fields=['ticket'], name='payment_tra_ticket__a40e3e_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx'), models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'), models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx'), models.Index(fields=['payment_method'], name='payment_tra_payment_45950f_idx')],
            },
        ),
    ]
