# Generated by Django 5.2.8 on 2025-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_admin_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('nfc_card', 'NFC Card'), ('digital_wallet', 'Digital Wallet'), ('bank_transfer', 'Bank Transfer'), ('admin_assigned', 'Admin Assigned'), ('paid_outside_system', 'Paid Outside System')], db_index=True, max_length=30),
        ),
    ]
