# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Company Finance',
                'verbose_name_plural': 'Company Finances',
                'db_table': 'company_finances',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='company_fin_date_4488ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('investment', 'Investment'), ('loan', 'Loan'), ('revenue', 'Revenue'), ('other', 'Other')], db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'db_table': 'deposits',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='deposits_date_7f8890_idx'), models.Index(fields=['source'], name='deposits_source_87d84f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(db_index=True, max_length=200)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Profit Share',
                'verbose_name_plural': 'Profit Shares',
                'db_table': 'profit_shares',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='profit_shar_date_1fff7b_idx'), models.Index(fields=['status'], name='profit_shar_status_8024f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfitWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('request_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Profit Withdrawal',
                'verbose_name_plural': 'Profit Withdrawals',
                'db_table': 'profit_withdrawals',
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['status'], name='profit_with_status_98b1c4_idx'), models.Index(fields=['request_date'], name='profit_with_request_fc8c28_idx'), models.Index(fields=['reference'], name='profit_with_referen_5edbac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'db_table': 'settlements',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='settlements_date_4f1fea_idx'), models.Index(fields=['status'], name='settlements_status_18dd5a_idx'), models.Index(fields=['reference'], name='settlements_referen_400af4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('operations', 'Operations'), ('technology', 'Technology'), ('staff', 'Staff'), ('office', 'Office'), ('other', 'Other')], db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='expenses_date_a77b87_idx'), models.Index(fields=['category'], name='expenses_categor_a6f264_idx'), models.Index(fields=['date', 'category'], name='expenses_date_3c6f66_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.organizer')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organizer'], name='payouts_organiz_1f7cc8_idx'), models.Index(fields=['status'], name='payouts_status_20cd29_idx'), models.Index(fields=['reference'], name='payouts_referen_ba227c_idx'), models.Index(fields=['created_at'], name='payouts_created_1441ca_idx')],
            },
        ),
    ]
