# Generated by Django 5.2.8 on 2025-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(db_index=True, help_text='Expense category (can be any value, not restricted to predefined choices)', max_length=50),
        ),
    ]
