# Generated by Django 5.2.8 on 2025-12-07 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_category_choices_restriction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the deduction', max_length=200)),
                ('value', models.DecimalField(decimal_places=2, help_text='Deduction value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('percentage', 'Percentage of Total Revenue'), ('fixed_per_ticket', 'Fixed Amount per Ticket Sold')], db_index=True, help_text='Type of deduction: percentage of total revenue or fixed amount per ticket', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this deduction is currently active')),
                ('description', models.TextField(blank=True, help_text='Optional description of the deduction')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'db_table': 'deductions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='deductions_is_acti_e577b4_idx'), models.Index(fields=['type'], name='deductions_type_fd1722_idx')],
            },
        ),
    ]
