# Generated by Django 5.2.8 on 2025-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='applies_to',
            field=models.CharField(choices=[('tickets', 'Tickets Sold Revenue'), ('nfc_cards', 'NFC Card Revenue')], db_index=True, default='tickets', help_text='Which revenue stream this deduction applies to', max_length=20),
        ),
    ]
