# Generated by Django 5.2.8 on 2025-12-09 11:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_add_applies_to_to_deduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_percentage', models.DecimalField(decimal_places=2, help_text="Owner's percentage share in the company (0-100)", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'db_table': 'owners',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='owners_status_9a6b69_idx'), models.Index(fields=['name'], name='owners_name_b96a82_idx'), models.Index(fields=['created_at'], name='owners_created_7f857a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current wallet balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='finances.owner')),
            ],
            options={
                'verbose_name': 'Owner Wallet',
                'verbose_name_plural': 'Owner Wallets',
                'db_table': 'owner_wallets',
            },
        ),
        migrations.CreateModel(
            name='OwnerWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('revenue_share', 'Revenue Share'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Wallet balance before this transaction', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction', max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_wallet_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.ownerwallet')),
            ],
            options={
                'verbose_name': 'Owner Wallet Transaction',
                'verbose_name_plural': 'Owner Wallet Transactions',
                'db_table': 'owner_wallet_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='ownerwallet',
            index=models.Index(fields=['owner'], name='owner_walle_owner_i_247f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerwallet',
            index=models.Index(fields=['last_updated'], name='owner_walle_last_up_de8880_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerwallettransaction',
            index=models.Index(fields=['wallet'], name='owner_walle_wallet__092a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerwallettransaction',
            index=models.Index(fields=['timestamp'], name='owner_walle_timesta_ea46e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerwallettransaction',
            index=models.Index(fields=['transaction_type'], name='owner_walle_transac_5c748b_idx'),
        ),
    ]
