# Generated by Django 5.2.8 on 2025-12-09 12:09

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_owner_ownerwallet_ownerwallettransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ticket Runners Wallet', max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current company wallet balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Company Wallet',
                'verbose_name_plural': 'Company Wallets',
                'db_table': 'company_wallet',
                'indexes': [models.Index(fields=['last_updated'], name='company_wal_last_up_9d7d23_idx')],
            },
        ),
    ]
