# Generated by Django 5.2.8 on 2025-12-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_companywallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companywallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current company wallet balance (can be negative)', max_digits=12),
        ),
    ]
