# Generated by Django 5.2.8 on 2025-12-09 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_companywallet_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total TR revenue that was distributed', max_digits=12)),
                ('total_distributed', models.DecimalField(decimal_places=2, help_text='Total amount distributed to owners', max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Amount that went to company wallet', max_digits=12)),
                ('distributed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_distributions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profit Distribution',
                'verbose_name_plural': 'Profit Distributions',
                'db_table': 'profit_distributions',
                'ordering': ['-distributed_at'],
                'indexes': [models.Index(fields=['distributed_at'], name='profit_dist_distrib_01010f_idx')],
            },
        ),
    ]
