# Generated by Django 5.2.8 on 2025-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_profitdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deduct_from_wallet',
            field=models.BooleanField(default=False, help_text='Whether to deduct this expense from a wallet'),
        ),
        migrations.AddField(
            model_name='expense',
            name='wallet_id',
            field=models.UUIDField(blank=True, help_text='ID of the wallet to deduct from (required if deduct_from_wallet is True)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='wallet_type',
            field=models.CharField(blank=True, choices=[('company', 'Company Wallet'), ('owner', 'Owner Wallet')], help_text='Type of wallet to deduct from', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ownerwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current wallet balance (can be negative)', max_digits=12),
        ),
    ]
