# Generated by Django 5.2.8 on 2025-11-06 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('payout_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchants',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['email'], name='merchants_email_fc58cd_idx'), models.Index(fields=['status'], name='merchants_status_c90f29_idx'), models.Index(fields=['verification_status'], name='merchants_verific_e4ee98_idx'), models.Index(fields=['registration_date'], name='merchants_registr_9d9985_idx')],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('registration_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
                'db_table': 'organizers',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['email'], name='organizers_email_33db09_idx'), models.Index(fields=['status'], name='organizers_status_bf2888_idx'), models.Index(fields=['verified'], name='organizers_verifie_627eae_idx'), models.Index(fields=['registration_date'], name='organizers_registr_792c8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('security', 'Security'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], db_index=True, default='active', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('performance', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='average', max_length=20)),
                ('hire_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usher',
                'verbose_name_plural': 'Ushers',
                'db_table': 'ushers',
                'ordering': ['-hire_date'],
                'indexes': [models.Index(fields=['status'], name='ushers_status_4ef2d7_idx'), models.Index(fields=['role'], name='ushers_role_264798_idx'), models.Index(fields=['email'], name='ushers_email_f2f55a_idx'), models.Index(fields=['hire_date'], name='ushers_hire_da_266585_idx')],
            },
        ),
    ]
