# Generated by Django 5.2.8 on 2025-11-06 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gmaps_location',
            field=models.CharField(blank=True, help_text='Google Maps location URL or coordinates', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, help_text='Mobile number for portal authentication', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for portal authentication', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='commercial_registration',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='contact_mobile',
            field=models.CharField(blank=True, db_index=True, help_text='Mobile number for portal authentication', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for portal authentication', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['phone'], name='merchants_phone_05e0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['mobile_number'], name='merchants_mobile__ba7702_idx'),
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['phone'], name='organizers_phone_0ae53c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['contact_mobile'], name='organizers_contact_e11319_idx'),
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['tax_id'], name='organizers_tax_id_803dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['commercial_registration'], name='organizers_commerc_50b8c5_idx'),
        ),
    ]
