# Generated by Django 5.2.8 on 2025-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_merchant_address_merchant_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usher',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
