# Generated by Django 5.2.8 on 2025-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0003_alter_usher_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usher',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events this usher is assigned to', related_name='ushers', to='events.event'),
        ),
    ]
