# Generated by Django 5.2.8 on 2025-11-17 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usher_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(blank=True, help_text='Manual merchant name if not selecting from dropdown', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for this location', max_length=20, null=True)),
                ('address', models.TextField(help_text='Full address of the merchant location')),
                ('google_maps_link', models.URLField(blank=True, help_text='Google Maps link or embed URL for this location', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this location is active and should be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(blank=True, help_text='Merchant this location belongs to (optional - can be manual entry)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Location',
                'verbose_name_plural': 'Merchant Locations',
                'db_table': 'merchant_locations',
                'ordering': ['merchant', 'address'],
                'indexes': [models.Index(fields=['merchant'], name='merchant_lo_merchan_729507_idx'), models.Index(fields=['is_active'], name='merchant_lo_is_acti_32f7c3_idx')],
            },
        ),
    ]
