# Generated by Django 5.2.8 on 2025-11-18 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merchantlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
