# Generated by Django 5.2.8 on 2025-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
