# Generated by Django 5.2.8 on 2025-11-18 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_phone_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('requested_data', models.JSONField(default=dict, help_text='Requested profile changes')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='organizer_requests/')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_edit_requests', to='users.organizer')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_organizer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizer Edit Request',
                'verbose_name_plural': 'Organizer Edit Requests',
                'db_table': 'organizer_edit_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organizer', 'status'], name='organizer_e_organiz_1adac4_idx'), models.Index(fields=['status', 'created_at'], name='organizer_e_status_a1b72b_idx')],
            },
        ),
    ]
