# Generated by Django 5.2.8 on 2025-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0006_add_transfer_fee_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('trending', 'Trending Events'), ('upcoming', 'Upcoming Events'), ('recommended', 'Recommended Events'), ('featured', 'Featured Event')], db_index=True, help_text='Unique identifier for the section', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Section title displayed on the home page', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Section subtitle/description', max_length=300)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order on the home page (lower numbers appear first)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this section is visible on the home page')),
                ('max_events', models.PositiveIntegerField(default=10, help_text='Maximum number of events to display in this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(blank=True, help_text='Events to display in this section', related_name='home_page_sections', to='events.event')),
            ],
            options={
                'verbose_name': 'Home Page Section',
                'verbose_name_plural': 'Home Page Sections',
                'db_table': 'home_page_sections',
                'ordering': ['order', 'section_key'],
                'indexes': [models.Index(fields=['section_key', 'is_active'], name='home_page_s_section_315ae7_idx'), models.Index(fields=['order', 'is_active'], name='home_page_s_order_8ef3d6_idx')],
            },
        ),
    ]
